# Generated by Django 5.2 on 2025-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventures',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
