# Generated by Django 5.2 on 2025-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_online', '0002_adventures_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventures',
            name='status',
            field=models.CharField(choices=[('miss', 'Отсутствует'), ('ready', 'Готов для игры'), ('in_progres', 'В разработке')], default='miss', max_length=20),
        ),
    ]
