# Generated by Django 5.2 on 2025-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_online', '0005_adventures_level_alter_adventures_type_adventure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventures',
            name='type_adventure',
            field=models.CharField(choices=[('Ваншот', 'Ваншот'), ('mini_company', 'Мини приключение'), ('company', 'Приключение')], default='oneshot', max_length=15),
        ),
    ]
